pub mod alloc;
mod rc;
mod security;
mod state;
mod scheduler;
mod vm;
mod inheritance;
mod pointers;
mod instance_repl_table;
mod instance_tag_collection;
mod rw_lock;
mod watchdog;
mod fastflags;
pub mod lua_macros;

pub(self) use instance_tag_collection::InstanceTagCollectionTable;
pub(self) use instance_repl_table::InstanceReplicationTable;
pub use inheritance::*;
pub use rc::*;
pub use vm::RobloxVM;
pub use rw_lock::*;
pub use state::{LuauState, registry_keys, get_current_identity, get_state, get_state_with_rwlock};
pub use scheduler::{ITaskScheduler, TaskScheduler, get_task_scheduler_from_lua, ParallelDispatch};
pub use security::*;
pub use fastflags::*;
pub(self) use pointers::*;
pub use watchdog::Watchdog;